version: "3.7"

services:

    wordpress:
      build: 
        context: .
        args:
        - USER_ID=1000
        - WP_LOCALE=en_GB
        - WP_VERSION=latest
      env_file:
        - .env
      environment:
        - DB_HOST=db
        - COMPOSER_AUTOLOAD_FILEPATH=/usr/local/src/vendor/autoload.php
      depends_on:
        - db
      volumes:
        - .:/usr/local/src
        - /var/www/html
        - ../lasntgadmin-itthinx-groups:/var/www/html/wp-content/plugins/groups
        - ../lasntgadmin-attendees:/var/www/html/wp-content/plugins/lasntgadmin-attendees
        - ../lasntgadmin-grant-funded-payment-gateway:/var/www/html/wp-content/plugins/lasntgadmin-grant-funded-payment-gateway
        - ../lasntgadmin-products:/var/www/html/wp-content/plugins/lasntgadmin-products
        - ../lasntgadmin-groups:/var/www/html/wp-content/plugins/lasntgadmin-groups
        - ../lasntgadmin-translate:/var/www/html/wp-content/plugins/lasntgadmin-translate
        - ../lasntgadmin-theme:/var/www/html/wp-content/themes/lasntgadmin-theme
      ports:
        - "9090:80"
        - "9443:443"

    db:
      image: mariadb:10.3
      environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=secret
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      volumes:
        - /var/lib/mysql
